INSERT INTO SPECJALNOSC (NAZWA) SELECT DISTINCT SPECIALITY FROM TEMP1;

INSERT INTO STANOWISKO (NAZWA) SELECT DISTINCT POSITION FROM TEMP1;

INSERT INTO PRACOWNIK2
(
SURNAME,
NAME,
BIRTH,
EMAIL,
HIRE,
SALARY,
ID_STANOWISKA,
ID_SPECJALNOSCI
)
SELECT 
TEMP1.SURNAME ,
TEMP1.NAME ,
TEMP1.BIRTH ,
TEMP1.EMAIL ,
TEMP1.HIRE_DATE AS HIRE,
TEMP1.SALARY ,
STANOWISKO.ID_STANOWISKA,
SPECJALNOSC.ID_SPECJALNOSCI
FROM TEMP1 
INNER JOIN STANOWISKO ON TEMP1.POSITION = STANOWISKO.NAZWA
INNER JOIN SPECJALNOSC ON TEMP1.SPECIALITY = SPECJALNOSC.NAZWA;

SELECT avgsal, idst, STANOWISKO.NAZWA  FROM (SELECT AVG(PRACOWNIK.SALARY) as avgsal, PRACOWNIK.ID_STANOWISKA as idst FROM PRACOWNIK
GROUP BY PRACOWNIK.ID_STANOWISKA) INNER JOIN STANOWISKO ON STANOWISKO.ID_STANOWISKA = IDST
WHERE STANOWISKO.NAZWA LIKE 'Education Analyst';

EXECUTE ZAD4ORAZ5.RESHAPE_DATA();