DROP TABLE PRACOWNIK;
DROP TABLE STANOWISKO;
DROP TABLE SPECJALNOSC;

CREATE TABLE STANOWISKO (
    ID_STANOWISKA NUMBER PRIMARY KEY,
    NAZWA VARCHAR(50)
);

CREATE TABLE SPECJALNOSC (
    ID_SPECJALNOSCI NUMBER PRIMARY KEY,
    NAZWA VARCHAR(50)
);

CREATE TABLE PRACOWNIK (
ID_PRACOWNIKA NUMBER PRIMARY KEY,
SURNAME VARCHAR(50),
NAME VARCHAR(50),
BIRTH DATE NOT NULL,
HIRE DATE NOT NULL,
EMAIL VARCHAR(50),
SALARY NUMBER NOT NULL,
ID_STANOWISKA REFERENCES STANOWISKO(ID_STANOWISKA),
ID_SPECJALNOSCI REFERENCES SPECJALNOSC(ID_SPECJALNOSCI)
);

CREATE SEQUENCE SEK_STANOWISKO;
CREATE SEQUENCE SEK_SPECJALNOSC;
CREATE SEQUENCE SEK_PRACOWNIK;

CREATE OR REPLACE TRIGGER T_USTAW_ID_STANOWISKO
BEFORE INSERT ON STANOWISKO
FOR EACH ROW
BEGIN
    :NEW.ID_STANOWISKA := SEK_STANOWISKO.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER T_USTAW_ID_SPECJALNOSC
BEFORE INSERT ON SPECJALNOSC
FOR EACH ROW
BEGIN
    :NEW.ID_SPECJALNOSCI := SEK_SPECJALNOSC.NEXTVAL;
END;
CREATE OR REPLACE TRIGGER T_USTAW_ID_PRACOWNIK
BEFORE INSERT ON PRACOWNIK
FOR EACH ROW
BEGIN
    :NEW.ID_PRACOWNIKA := SEK_PRACOWNIK.NEXTVAL;
END;

SELECT * FROM Pracownik;
SELECT * FROM Stanowisko;
SELECT * FROM Specjalnosc;

EXECUTE zad4oraz5.RESHAPE_DATA();

zad4oraz5.avg_salary('Education Analyst');